iep_projekat/WebRole1/Models/Kanal.cs
namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Kanal")]
    public partial class Kanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kanal()
        {
            Odgovors = new HashSet<Odgovor>();
            Pratis = new HashSet<Prati>();
            Klons = new HashSet<Klon>();
        }

        [Key]
        public int IdKan { get; set; }

        [Required]
        [StringLength(50)]
        public string Naziv { get; set; }

        [Display(Name = "Vreme Otvaranja")]
        public DateTime VrOtvaranja { get; set; }

        [Display(Name = "Vreme Zatvaranja")]
        public DateTime? VrZatvaranja { get; set; }

        [Required]
        [StringLength(50)]
        public string Lozinka { get; set; }

        public string Status { get; set; }

        [Display(Name = "Vremenski Ogranicen")]
        public bool VrOgranicen { get; set; }

        public int? IntervalTrajanja { get; set; }

        public int IdKor { get; set; }

        public virtual Korisnik Korisnik { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovors { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prati> Pratis { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klon> Klons { get; set; }
    }
}

iep_projekat/WebRole1/Controllers/KanalsController.cs
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRole1.Hubs;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class KanalsController : Controller
    {
        private baza db = new baza();

        private void CloseChannels()
        {
            List<Kanal> kanals = db.Kanals.Where(p => p.VrOgranicen == true).Where(p => p.Status == "Otvoren").ToList();
            foreach (var kanal in kanals)
            {
                TimeSpan minutesPast = DateTime.Now - kanal.VrOtvaranja;
                if (minutesPast.TotalMinutes > kanal.IntervalTrajanja)
                {
                    kanal.VrZatvaranja = kanal.VrOtvaranja.AddMinutes((double)kanal.IntervalTrajanja);
                    kanal.Status = "Zatvoren";

                    db.Entry(kanal).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
        }

        // GET: Kanals
        public ActionResult Index()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();
            Korisnik korisnik = getKorisnik();
            var kanals = db.Kanals.Where(p => p.IdKor == korisnik.IdKor).Include(k => k.Korisnik);

            return View(kanals.ToList());
        }

        // GET: Kanals/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kanal kanal = db.Kanals.Find(id);
            if (kanal == null)
            {
                return HttpNotFound();
            }
            return View(kanal);
        }

        // GET: Kanals/Create
        public ActionResult Create()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime");
            ViewBag.Status = new SelectList(new List<string> { "Na cekanju", "Otvoren", "Zatvoren" });
            return View();
        }

        // POST: Kanals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdKan,Naziv,Lozinka,Status,VrOgranicen,IntervalTrajanja")] Kanal kanal)
        {
            if (ModelState.IsValid)
            {
                Korisnik korisnik = getKorisnik();

                kanal.VrOtvaranja = DateTime.Now;
                kanal.IdKor = korisnik.IdKor;
                if (kanal.Status == "Zatvoren")
                    kanal.VrZatvaranja = DateTime.Now;

                db.Kanals.Add(kanal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Status = new SelectList(new List<string> { "Na cekanju", "Otvoren", "Zatvoren" });
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", kanal.IdKor);
            return View(kanal);
        }

        // GET: Kanals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kanal kanal = db.Kanals.Find(id);
            if (kanal == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", kanal.IdKor);
            ViewBag.Status = new SelectList(new List<string> { "Na cekanju", "Otvoren", "Zatvoren" }, kanal.Status);
            return View(kanal);
        }

        // POST: Kanals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdKan,IdKor,Naziv,VrOtvaranja,VrZatvaranja,Lozinka,Status,VrOgranicen,IntervalTrajanja")] Kanal kanal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kanal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", kanal.IdKor);
            return View(kanal);
        }

        // GET: Kanals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kanal kanal = db.Kanals.Find(id);
            if (kanal == null)
            {
                return HttpNotFound();
            }
            return View(kanal);
        }

        // POST: Kanals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kanal kanal = db.Kanals.Find(id);
            db.Kanals.Remove(kanal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public Korisnik getKorisnik()
        {
            if (Session["email"] != null)
            {
                string email = Session["email"].ToString();
                Korisnik korisnik = db.Korisniks.Where(a => a.Email.Equals(email)).FirstOrDefault<Korisnik>();

                return korisnik;
            }
            else
            {
                return null;
            }
        }

        public ActionResult PublishList(int id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();

            Korisnik korisnik = getKorisnik();
            var pitanjes = db.Pitanjes.Where(p => p.IdKor == korisnik.IdKor).Where(p => p.Zakljucano == true).Include(p => p.Korisnik);
            Kanal channel = db.Kanals.Find(id);
            ViewBag.ChannelName = channel.Naziv;
            ViewBag.ChannelId = id;
            ViewBag.UserId = korisnik.IdKor;
            return View(pitanjes.ToList());
        }

        [HttpPost, ActionName("PublishList")]
        [ValidateAntiForgeryToken]
        public ActionResult Publish(int id, int? IdPit)
        {
            Pitanje pitanje = db.Pitanjes.Find(IdPit);
            Kanal kanal = db.Kanals.Find(id);
            Klon klon = new Klon();

            klon.IdPit = pitanje.IdPit;
            klon.Naslov = pitanje.Naslov;
            klon.Tekst = pitanje.Tekst;
            klon.Slika = pitanje.Slika;
            klon.ImageToUpload = pitanje.ImageToUpload;
            klon.VrPravljenja = pitanje.VrPravljenja;
            klon.VrPoslZaklj = pitanje.VrPoslZaklj;
            klon.Zakljucano = pitanje.Zakljucano;
            klon.IdKan = id;

            db.Klons.Add(klon);
            db.SaveChanges();

            var ponudjeniOdgs = db.PonudjeniOdgs.Where(p => p.IdPit == pitanje.IdPit).ToList();
            string stringPonudjeni = "";
            foreach (var ponudjeni in ponudjeniOdgs)
            {
                KlonPonudjeniOdg klonPonudjeni = new KlonPonudjeniOdg();
                klonPonudjeni.Sadrzaj = ponudjeni.Sadrzaj;
                klonPonudjeni.RedniBr = ponudjeni.RedniBr;
                klonPonudjeni.Tacan = ponudjeni.Tacan;
                klonPonudjeni.IdKlo = klon.IdKlo;
                stringPonudjeni += klonPonudjeni.Sadrzaj + ";";
                db.KlonPonudjeniOdgs.Add(klonPonudjeni);
            }

            db.SaveChanges();

            //SignalR
            var context = GlobalHost.ConnectionManager.GetHubContext<PushHub>();
            context.Clients.Group("Channel " + id).addNewQuestion(klon.Naslov, klon.Tekst, stringPonudjeni, klon.IdKlo, kanal.Naziv);

            return RedirectToAction("PublishList");
        }

        public ActionResult PublishedQuestions(int idKan)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();

            var klones = db.Klons.Where(p => p.IdKan == idKan);
            ViewBag.IdKan = idKan;
            return View(klones.ToList());
        }

        public ActionResult ChannelsStudent()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            CloseChannels();

iep_projekat/WebRole1/Views/Kanals/Answers.cshtml
@model IEnumerable<WebRole1.Models.Odgovor>

@{
    ViewBag.Title = "Answers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Answers</h2>

@Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })
<br/> <br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
            @*@Html.DisplayNameFor(model => model.Kanal.Naziv)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrSlanja)
            @*@Html.DisplayNameFor(model => model.Klon.Naslov)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KlonPonudjeniOdg.RedniBr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KlonPonudjeniOdg.Sadrzaj)
        </th>
        @*<th>

        </th>
        <th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr @if (item.KlonPonudjeniOdg.Tacan) { <text>style="background-color: lightgreen"</text> }else{ <text>style="background-color: lightcoral"</text>}>
            <td>
                @Html.DisplayFor(modelItem => item.Korisnik.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrSlanja)
            </td>
            <td>
                @(item.KlonPonudjeniOdg.RedniBr+1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KlonPonudjeniOdg.Sadrzaj)
            </td>
            @*<td>
        @Html.DisplayFor(modelItem => item.VrSlanja)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
    </td>*@
        </tr>
    }

</table>

iep_projekat/WebRole1/Views/Kanals/ChannelsStudent.cshtml
@model IEnumerable<WebRole1.Models.Kanal>

@{
    ViewBag.Title = "Channels";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Channels</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdKan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrOtvaranja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrZatvaranja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            Broj Prijavljenih
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdKan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrOtvaranja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrZatvaranja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pratis.Count)
            </td>
            <td>
                <input id="IdPit" name="IdPit" type="hidden" value=@item.IdKan />
                @{ int idK = item.IdKan;}
                @if (item.Pratis.Where(p => p.IdKor == ViewBag.IdKor).Count() == 1)
                {
                    <input type="button" value="Subscribed" class="btn btn-default" onclick="window.location.href='/Kanals/Subscribe?idKan=@item.IdKan'" disabled="disabled"/>
                }
                else
                {
                    <input type="button" value="Subscribe" class="btn btn-default" onclick="window.location.href='/Kanals/Subscribe?idKan=@item.IdKan'" />
                }
            </td>
        </tr>
    }

</table>

iep_projekat/WebRole1/Views/Kanals/Create.cshtml
@model WebRole1.Models.Kanal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create channel</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kanal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lozinka, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Lozinka, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrOgranicen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VrOgranicen, new { htmlAttributes = new { @onchange = "change()" } })
                    @Html.ValidationMessageFor(model => model.VrOgranicen, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IntervalTrajanja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IntervalTrajanja, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.IntervalTrajanja, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IdKor, "IdKor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKor, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    function change() {
        checkbox = document.getElementById("VrOgranicen");
        textbox = document.getElementById("IntervalTrajanja");
        if (checkbox.checked) {
            textbox.disabled = false;
            textbox.value = 10;
        }
        else {
            textbox.disabled = true;
            textbox.value = null;
        }
    }
</script>

iep_projekat/WebRole1/Views/Kanals/Delete.cshtml
@model WebRole1.Models.Kanal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kanal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrOtvaranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrOtvaranja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrZatvaranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrZatvaranja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lozinka)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lozinka)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrOgranicen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrOgranicen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IntervalTrajanja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IntervalTrajanja)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iep_projekat/WebRole1/Views/Kanals/Details.cshtml
@model WebRole1.Models.Kanal

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Kanal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrOtvaranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrOtvaranja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrZatvaranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrZatvaranja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lozinka)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lozinka)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrOgranicen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrOgranicen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IntervalTrajanja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IntervalTrajanja)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdKan }) |
    @Html.ActionLink("Back to List", "Index")
</p>

iep_projekat/WebRole1/Views/Kanals/Index.cshtml
@model IEnumerable<WebRole1.Models.Kanal>

@{
    ViewBag.Title = "Channels";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Channels</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdKan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrOtvaranja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrZatvaranja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            Broj Prijavljenih
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdKan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VrOtvaranja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VrZatvaranja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pratis.Count)
        </td>
        <td>
            @if(item.Status == "Zatvoren")
            {
                @Html.DisplayName("Edit")
            }
            else
            {
                @Html.ActionLink("Edit", "Edit", new { id=item.IdKan })
            }
             | @Html.ActionLink("Details", "Details", new { id = item.IdKan }) |
            @Html.ActionLink("Publishing", "PublishList", new { id=item.IdKan })
        </td>
    </tr>
}

</table>

iep_projekat/WebRole1/Views/Kanals/Subscribe.cshtml
@model WebRole1.Models.Kanal

@{
    ViewBag.Title = "Subscribe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Subscribe</h2>

<div class="row">
    <div class="col-md-8">
        @*<section id="loginForm">*@
            @using (Html.BeginForm(@*"Subscribe", "Kanals", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }*@))
            {
                @Html.AntiForgeryToken()
                <h4>Channel @ViewBag.ChannelName</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Lozinka, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Lozinka, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @{ int num = Convert.ToInt32(@ViewBag.E); }
                            @Html.CheckBox("Evaluation")
                            @Html.Label("Yes, I want automatic evaluation for " + num + " tokens")
                        </div>
                    </div>
                </div> 
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Subscribe" class="btn btn-default" />
                    </div>
                </div>
            }
        @*</section>*@
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}