iep_projekat/WebRole1/Models/Klon.cs
namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("Klon")]
    public partial class Klon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klon()
        {
            Odgovors = new HashSet<Odgovor>();
            KlonPonudjeniOdgs = new HashSet<KlonPonudjeniOdg>();
        }

        [Required]
        [StringLength(80)]
        public string Naslov { get; set; }

        [Column(TypeName = "text")]
        public string Tekst { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageToUpload { get; set; }

        public byte[] Slika { get; set; }

        [Display(Name = "Vreme Pravljenja")]
        public DateTime? VrPravljenja { get; set; }

        [Display(Name = "Vreme Zakljucavanja")]
        public DateTime? VrPoslZaklj { get; set; }

        public bool Zakljucano { get; set; }

        public int IdPit { get; set; }

        [Key]
        public int IdKlo { get; set; }

        public int? IdKan { get; set; }

        public virtual Kanal Kanal { get; set; }

        public virtual Pitanje Pitanje { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovors { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlonPonudjeniOdg> KlonPonudjeniOdgs { get; set; }
    }
}

iep_projekat/WebRole1/Controllers/KlonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class KlonsController : Controller
    {
        private baza db = new baza();

        public Korisnik getKorisnik()
        {
            if (Session["email"] != null)
            {
                using (baza db = new baza())
                {
                    string email = Session["email"].ToString();
                    Korisnik korisnik = db.Korisniks.Where(a => a.Email.Equals(email)).FirstOrDefault<Korisnik>();

                    return korisnik;
                }
            }
            else
            {
                return null;
            }
        }

        // GET: Klons
        public ActionResult Index()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            var klons = db.Klons.Include(k => k.Kanal).Include(k => k.Pitanje);
            return View(klons.ToList());
        }

        // GET: Klons/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klon klon = db.Klons.Find(id);
            if (klon == null)
            {
                return HttpNotFound();
            }
            ViewBag.K = db.Parametris.FirstOrDefault().K;
            return View(klon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int answer, string IdKlo)
        {
            int idKlo = Convert.ToInt32(IdKlo);

            Korisnik korisnik = getKorisnik();
            Klon klon = db.Klons.Find(idKlo);
            Prati prati = db.Pratis.Where(p => p.IdKor == korisnik.IdKor).Where(p => p.IdKan == klon.IdKan).FirstOrDefault();
            KlonPonudjeniOdg ponudjeni = db.KlonPonudjeniOdgs.Where(p => p.IdKlo == idKlo).Where(p => p.RedniBr == answer).FirstOrDefault();
            Odgovor odgovor = new Odgovor();
            odgovor.IdKlo = idKlo;
            odgovor.IdKor = korisnik.IdKor;
            odgovor.VrSlanja = DateTime.Now;
            odgovor.IdKPO = ponudjeni.IdKPO;
            odgovor.IdKan = (int)klon.IdKan;

            db.Odgovors.Add(odgovor);
            db.SaveChanges();

            if(prati.Evaluacija == true)
            {
                if (ponudjeni.Tacan == true)
                    return RedirectToAction("Correct", new { questionId = klon.IdKlo, answer = answer});
                else
                    return RedirectToAction("Wrong", new { questionId = klon.IdKlo, answer = answer });
            }
            else
            {
                return RedirectToAction("Success");
            }
        }

        // GET: Klons/Create
        public ActionResult Create()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            ViewBag.IdKan = new SelectList(db.Kanals, "IdKan", "Naziv");
            ViewBag.IdPit = new SelectList(db.Pitanjes, "IdPit", "Naslov");
            return View();
        }

        // POST: Klons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdKlo,Naslov,Tekst,Slika,VrPravljenja,VrPoslZaklj,Zakljucano,IdPit,IdKan")] Klon klon)
        {
            if (ModelState.IsValid)
            {
                db.Klons.Add(klon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdKan = new SelectList(db.Kanals, "IdKan", "Naziv", klon.IdKan);
            ViewBag.IdPit = new SelectList(db.Pitanjes, "IdPit", "Naslov", klon.IdPit);
            return View(klon);
        }

        // GET: Klons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klon klon = db.Klons.Find(id);
            if (klon == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKan = new SelectList(db.Kanals, "IdKan", "Naziv", klon.IdKan);
            ViewBag.IdPit = new SelectList(db.Pitanjes, "IdPit", "Naslov", klon.IdPit);
            return View(klon);
        }

        // POST: Klons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdKlo,Naslov,Tekst,Slika,VrPravljenja,VrPoslZaklj,Zakljucano,IdPit,IdKan")] Klon klon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(klon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKan = new SelectList(db.Kanals, "IdKan", "Naziv", klon.IdKan);
            ViewBag.IdPit = new SelectList(db.Pitanjes, "IdPit", "Naslov", klon.IdPit);
            return View(klon);
        }

        // GET: Klons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klon klon = db.Klons.Find(id);
            if (klon == null)
            {
                return HttpNotFound();
            }
            return View(klon);
        }

        // POST: Klons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Klon klon = db.Klons.Find(id);
            db.Klons.Remove(klon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Success()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            return View();
        }

        public  ActionResult Correct(int questionId, int answer)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Klon question = db.Klons.Find(questionId);
            ViewBag.K = db.Parametris.FirstOrDefault().K;
            ViewBag.Answer = answer;

            return View(question);
        }

        public ActionResult Wrong(int questionId, int answer)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Klon question = db.Klons.Find(questionId);
            ViewBag.K = db.Parametris.FirstOrDefault().K;
            ViewBag.Answer = answer;

            return View(question);
        }

        public ActionResult History()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Korisnik korisnik = getKorisnik();
            ViewBag.IdKor = korisnik.IdKor;
            var clones = db.Klons.SqlQuery("select k.* from Klon k, Odgovor o where k.IdKlo = o.IdKlo and o.IdKor=" + korisnik.IdKor+" order by o.VrSlanja desc").ToList();
            return View(clones);
        }

        public ActionResult HistoryDetails(int id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "student")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Korisnik korisnik = getKorisnik();
            Klon klon = db.Klons.Find(id);
            var odgovor = db.Odgovors.Where(p => p.IdKlo == klon.IdKlo).Where(p => p.IdKor == korisnik.IdKor).FirstOrDefault();

            ViewBag.K = db.Parametris.FirstOrDefault().K;
            ViewBag.Answer = odgovor.KlonPonudjeniOdg.RedniBr;

            return View(klon);
        }
    }

}

iep_projekat/WebRole1/Views/Klons/Correct.cshtml
@model WebRole1.Models.Klon

@{
    ViewBag.Title = "Correct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Correct!</h2>

<br />
<h4>Channel: @Model.Kanal.Naziv</h4>

<div class="row" id="boxes">

    <div class="col-md-8" style="padding: 0px" id="question">
        <div class="box">
            <h2>
                @Html.DisplayFor(model => model.Naslov)
            </h2>
            <br />
            <p>
                @Html.DisplayFor(model => model.Tekst)
            </p>
            @if (Model.Slika != null)
            {
                <div class="image" align="center">
                    @HtmlHelpers.ShowImage(Model.Slika)
                </div>
            }
            <div class="ponudjeni">
                <ul>
                    @for (int i = 0; i < Convert.ToInt32(ViewBag.K); i++)
                    {
                        if(ViewBag.Answer == i)
                        {
                            <li style="background-color: lightgreen">
                                @(i + 1))
                                @Model.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                            </li>
                        }
                        else
                        {
                            <li>
                                @(i + 1))
                                @Model.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                            </li>
                        }
                    }
                </ul>
            </div>

        </div>
    </div>
    @*@if (Model.Slika != null)
    {
        <div class="col-md-4">
            <div class="box">
                @HtmlHelpers.ShowImage(Model.Slika);
            </div>
        </div>
    }*@

</div>

<br />

@Html.ActionLink("Back to the Blackboard", "Blackboard", "Home")

<style media="screen" type="text/css">
    .box p {
        word-wrap: break-word;
        font-size: 18px;
        padding-left: 25px;
        padding-right: 25px;
    }

    .box h2 {
        text-align: center;
        font-weight: bold;
        padding-bottom: 25px;
    }

    .box {
        padding-top: 10px;
        padding-left: 15px;
        padding-right: 15px;
        border: 3px solid lightgreen;
        border-radius: 16px;
        min-height: 400px;
        margin: 2px;
    }

    .ponudjeni {
        padding-top: 25px;
        /*padding-left: 40px;
        padding-right: 30px;*/
        font-size: 15px;
        word-wrap: break-word;
    }

    #question {
        margin: auto;
    }

    .ponudjeni ul {
        padding-left: 70px;
        padding-bottom: 20px;
        list-style-type: none;
    }

    .ponudjeni li {
        padding-bottom: 10px;
        padding-right: 25px;
        /*vertical-align: middle;*/
    }

    input[type="radio"] {
        margin-top: 1px;
    }
</style>

iep_projekat/WebRole1/Views/Klons/Create.cshtml
@model WebRole1.Models.Klon

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Klon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naslov, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tekst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tekst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tekst, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slika, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slika, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrPravljenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrPravljenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VrPravljenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrPoslZaklj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrPoslZaklj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VrPoslZaklj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zakljucano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Zakljucano)
                    @Html.ValidationMessageFor(model => model.Zakljucano, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdPit, "IdPit", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPit", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdPit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdKan, "IdKan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKan", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iep_projekat/WebRole1/Views/Klons/Delete.cshtml
@model WebRole1.Models.Klon

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Klon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kanal.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kanal.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pitanje.Naslov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pitanje.Naslov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naslov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tekst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tekst)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slika)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPravljenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPravljenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPoslZaklj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPoslZaklj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zakljucano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zakljucano)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iep_projekat/WebRole1/Views/Klons/Details.cshtml
@model WebRole1.Models.Klon

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<br />
<h4>Channel: @Model.Kanal.Naziv</h4>

<div class="row" id="boxes">
        
        <div class="col-md-8" style="padding: 0px" id="question">
            <div class="box">
                <h2>
                    @Html.DisplayFor(model => model.Naslov)
                </h2>
                <br />
                <p>
                    @Html.DisplayFor(model => model.Tekst)
                </p>
                @if(Model.Slika != null)
                {
                    <div class="image" align="center">
                        @HtmlHelpers.ShowImage(Model.Slika)
                    </div>
                }

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.IdKlo)
                    <div class="ponudjeni">
                        <ul>
                            @for (int i = 0; i < Convert.ToInt32(ViewBag.K); i++)
                            {
                                <li>
                                    @Html.RadioButton("answer", i) &nbsp
                                    @(i+1))
                                    @Model.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                                </li>
                            }
                        </ul>
                    </div>

                    <div class="form-group">
                        <div align="center">
                            <input type="submit" value="Submit" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
        </div>
        @*@if(Model.Slika != null)
        {
            <div class="col-md-4">
                <div class="box">
                        @HtmlHelpers.ShowImage(Model.Slika);
                </div>
            </div>
        }*@
    
</div>
<br />
@Html.ActionLink("Back to the Blackboard", "Blackboard", "Home")
<style media="screen" type="text/css">
    .box p {
        word-wrap: break-word;
        font-size: 18px;
        padding-left: 25px;
        padding-right: 25px;
    }

    .box h2 {
        text-align: center;
        font-weight: bold;
        padding-bottom: 25px;
    }

    .box {
        padding-top: 10px;
        padding-left: 15px;
        padding-right: 15px;
        border: 3px solid silver;
        border-radius: 16px;
        min-height: 400px;
        margin: 2px;
    }

    .ponudjeni {
        padding-top: 25px;
        /*padding-left: 40px;
        padding-right: 30px;*/
        font-size: 15px;
        word-wrap: break-word;
    }

    #question{
        margin: auto;
    }

    .ponudjeni ul{
        padding-left: 70px;
        padding-bottom: 20px;
        list-style-type: none;
    }
    .ponudjeni li{
        padding-bottom: 10px;
        padding-right: 25px;
        /*vertical-align: middle;*/
    }

    input[type="radio"] {
        margin-top: 1px;
    }

    .image {
        margin: auto;
    }
</style>

iep_projekat/WebRole1/Views/Klons/History.cshtml
@model IEnumerable<WebRole1.Models.Klon>

@{
    ViewBag.Title = "History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>History</h2>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kanal.IdKan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kanal.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naslov)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Tekst)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.Odgovors.Where(p => p.IdKlo == model.IdKlo).Where(p => p.IdKor == ViewBag.IdKor).FirstOrDefault().VrSlanja)*@
            Vreme odgovora
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Kanal.IdKan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kanal.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naslov)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Tekst)
            </td>*@
            <td>
                @*@Html.DisplayFor(modelItem => item.VrPravljenja)*@
                @{ int id = ViewBag.IdKor;}
                @Html.DisplayFor(modelItem => item.Odgovors.Where(p => p.IdKlo == item.IdKlo).Where(p => p.IdKor == id).FirstOrDefault().VrSlanja)
            </td>
            <td>
                @Html.ActionLink("Details", "HistoryDetails", new { id = item.IdKlo }) 
            </td>
        </tr>
    }

</table>

iep_projekat/WebRole1/Views/Klons/HistoryDetails.cshtml
@model WebRole1.Models.Klon

@{
    ViewBag.Title = "HistoryDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HistoryDetails</h2>
<br />
<h4>Channel: @Model.Kanal.Naziv</h4>

<div class="row" id="boxes">

    <div class="col-md-8" style="padding: 0px" id="question">
        <div class="box">
            <h2>
                @Html.DisplayFor(model => model.Naslov)
            </h2>
            <br />
            <p>
                @Html.DisplayFor(model => model.Tekst)
            </p>
            @if (Model.Slika != null)
            {
                <div class="image" align="center">
                    @HtmlHelpers.ShowImage(Model.Slika)
                </div>
            }
            <div class="ponudjeni">
                <ul>
                    @for (int i = 0; i < Convert.ToInt32(ViewBag.K); i++)
                    {
                        if (ViewBag.Answer == i)
                        {
                            <li style="background-color: lightblue">
                                @(i + 1))
                                @Model.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                            </li>
                        }
                        else
                        {
                            <li>
                                @(i + 1))
                                @Model.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                            </li>
                        }
                    }
                </ul>
            </div>

        </div>
    </div>
    @*@if (Model.Slika != null)
        {
            <div class="col-md-4">
                <div class="box">
                    @HtmlHelpers.ShowImage(Model.Slika);
                </div>
            </div>
        }*@

</div>

<br />

@Html.ActionLink("Back to History", "History", "Klons")

<style media="screen" type="text/css">
    .box p {
        word-wrap: break-word;
        font-size: 18px;
        padding-left: 25px;
        padding-right: 25px;
    }

    .box h2 {
        text-align: center;
        font-weight: bold;
        padding-bottom: 25px;
    }

    .box {
        padding-top: 10px;
        padding-left: 15px;
        padding-right: 15px;
        border: 3px solid lightblue;
        border-radius: 16px;
        min-height: 400px;
        margin: 2px;
    }

    .ponudjeni {
        padding-top: 25px;
        /*padding-left: 40px;
        padding-right: 30px;*/
        font-size: 15px;
        word-wrap: break-word;
    }

    #question {
        margin: auto;
    }

    .ponudjeni ul {
        padding-left: 70px;
        padding-bottom: 20px;
        list-style-type: none;
    }

    .ponudjeni li {
        padding-bottom: 10px;
        padding-right: 25px;
        /*vertical-align: middle;*/
    }

    input[type="radio"] {
        margin-top: 1px;
    }
</style>

iep_projekat/WebRole1/Views/Klons/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Success!</h2>

<h3>Answer is successfully sent!</h3>
<br />
@Html.ActionLink("Back to the Blackboard", "Blackboard", "Home")