iep_projekat/WebRole1/Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class KorisniksController : Controller
    {
        private baza db = new baza();

        // GET: Korisniks
        public ActionResult Index()
        {
            return View(db.Korisniks.ToList());
        }

        // GET: Korisniks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // GET: Korisniks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Korisniks.Add(korisnik);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "admin")
            {
                return RedirectToAction("UnauthorizedAccess", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            ViewBag.Status = new SelectList(new List<string> { "aktivan", "neaktivan"}, korisnik.Status);
            ViewBag.Uloga = new SelectList(new List<string> { "student", "profesor" }, korisnik.Uloga);

            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Korisnik korisnik)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "admin")
            {
                return RedirectToAction("UnauthorizedAccess", "Home");
            }

            korisnik.PotvrdaLozinke = korisnik.Lozinka;
            db.Entry(korisnik).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Registrations", "Home");
        }

        // GET: Korisniks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisniks.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Korisnik korisnik = db.Korisniks.Find(id);
            db.Korisniks.Remove(korisnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iep_projekat/WebRole1/Controllers/NarudzbinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class NarudzbinasController : Controller
    {
        private baza db = new baza();

        // GET: Narudzbinas
        public ActionResult Index()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() == "admin")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            string email = Session["email"].ToString();
            Korisnik korisnik = db.Korisniks.Where(a => a.Email.Equals(email)).FirstOrDefault<Korisnik>();
            int idKor = korisnik.IdKor;

            var narudzbinas = db.Narudzbinas.Include(n => n.Korisnik).Where(a => a.IdKor == idKor);
            return View(narudzbinas.ToList());
        }

        // GET: Narudzbinas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Narudzbina narudzbina = db.Narudzbinas.Find(id);
            if (narudzbina == null)
            {
                return HttpNotFound();
            }
            return View(narudzbina);
        }

        // GET: Narudzbinas/Create
        public ActionResult Create()
        {
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime");
            return View();
        }

        // POST: Narudzbinas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdNar,BrTokena,Cena,Status,IdKor")] Narudzbina narudzbina)
        {
            if (ModelState.IsValid)
            {
                db.Narudzbinas.Add(narudzbina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", narudzbina.IdKor);
            return View(narudzbina);
        }

        // GET: Narudzbinas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Narudzbina narudzbina = db.Narudzbinas.Find(id);
            if (narudzbina == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", narudzbina.IdKor);
            return View(narudzbina);
        }

        // POST: Narudzbinas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdNar,BrTokena,Cena,Status,IdKor")] Narudzbina narudzbina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(narudzbina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", narudzbina.IdKor);
            return View(narudzbina);
        }

        // GET: Narudzbinas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Narudzbina narudzbina = db.Narudzbinas.Find(id);
            if (narudzbina == null)
            {
                return HttpNotFound();
            }
            return View(narudzbina);
        }

        // POST: Narudzbinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Narudzbina narudzbina = db.Narudzbinas.Find(id);
            db.Narudzbinas.Remove(narudzbina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iep_projekat/WebRole1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

iep_projekat/WebRole1/Views/Home/AccountDetails.cshtml
@model WebRole1.Models.Korisnik

@{
    ViewBag.Title = "AccountDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AccountDetails</h2>

<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrTokena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrTokena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uloga)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uloga)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

iep_projekat/WebRole1/Views/Home/Blackboard.cshtml
@model IEnumerable<WebRole1.Models.Klon>

@{
    ViewBag.Title = "Blackboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Blackboard</h2>
<br />

<div class="row" id="boxes">
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="padding: 0px">
            <div class="box" id="pit_@item.IdKlo">
                <h4>@item.Naslov</h4>
                <br />
                <p>
                    @item.Tekst
                </p>
                <div class="ponudjeni">
                    <ol>
                        @for (int i = 0; i < Convert.ToInt32(ViewBag.K); i++)
                        {
                            <li>
                                @item.KlonPonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj
                            </li>
                        }
                    </ol>
                </div>
                <div class="footer">@item.Kanal.Naziv</div>
            </div>
        </div>
    }
</div>
<input id="IdKor" name="IdKor" type="hidden" value=@ViewBag.UserId />

<style media="screen" type="text/css">
    .box p {
        word-wrap: break-word;
    }

    .box h4 {
        text-align: center
    }

    .box {
        padding-top: 10px;
        padding-left: 15px;
        padding-right: 15px;
        border: 3px solid silver;
        border-radius: 15px;
        height: 300px;
        margin: 2px;
        cursor: pointer;
    }

    .ponudjeni {
        padding-top: 25px;
        /*padding-left: 40px;
        padding-right: 30px;*/
        font-size: 12px;
        word-wrap: break-word;
    }

    .footer {
        font-size: 10px;
        position: absolute;
        bottom: 10px;
        left: 12px;
    }

</style>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var push = $.connection.pushHub;
            // Create a function that the hub can call back to display messages.
            //$.connection.hub.qs = {"UserEmail" : }
            $.connection.hub.start().done(function () {
                push.server.joinGroup($('#IdKor').val());
            });
            //$.connection.hub.start();
            push.client.addNewQuestion = function (naslov, tekst, ponudjeni, idPit, kanal) {
                // Add the message to the page.
                ponudjeni = ponudjeni.substring(0, ponudjeni.length - 1);
                var odgovori = ponudjeni.split(";");
                var htmlOdgovori = "";
                for (var i in odgovori) {
                    htmlOdgovori += "<li> " + odgovori[i] + "</li>";
                }
                $('#boxes').prepend('<div class="col-md-4" style="padding: 0px"> <div class="box" id="pit_' + idPit + '" onclick="dodato('+idPit+')"> <h4>' + htmlEncode(naslov) + '</h4> <br/> <p>' + htmlEncode(tekst) + '</p><div class="ponudjeni" ><ol>' + htmlOdgovori + '</ol></div><div class="footer">'+kanal+'</div></div></div>');

            };

        });

        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }

        $('[id^="pit"').on('click', function (event) {
            var id = event.currentTarget.id.toString();
            id = id.substring(4, id.length);
            window.location.href = '/Klons/Details/' + id;

        });

        //$('[id^="pit"').click(function (event) {
        //    var id = event.currentTarget.id.toString();
        //    id = id.substring(4, id.length);
        //    window.location.href = '/Klons/Details/' + id;

        //});
        function dodato(idPit) {
            window.location.href = '/Klons/Details/' + idPit;

        }
    </script>
}

iep_projekat/WebRole1/Views/Home/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}
<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

iep_projekat/WebRole1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

iep_projekat/WebRole1/Views/Home/FailedPurchase.cshtml
@{
    ViewBag.Title = "Neuspela kupovina";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Neuspela kupovina!</h1>

iep_projekat/WebRole1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>neLearning</h1>
    <p class="lead">neLearning is a free web portal for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="/Home/Login" class="btn btn-primary btn-lg">Get Started &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

iep_projekat/WebRole1/Views/Home/Login.cshtml
@model WebRole1.Models.Korisnik

@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Lozinka, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Lozinka, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <!--<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            Html.CheckBoxFor(model => m.RememberMe)
                            Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div> -->
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
                <!--
                <p>
                    Html.ActionLink("Forgot your password?", "ForgotPassword")
                </p>-->
            }
        </section>
    </div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

iep_projekat/WebRole1/Views/Home/Register.cshtml
@model WebRole1.Models.Korisnik

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h4>Create a new account</h4>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lozinka, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lozinka, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotvrdaLozinke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotvrdaLozinke, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.PotvrdaLozinke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

iep_projekat/WebRole1/Views/Home/Registrations.cshtml
@model IEnumerable<WebRole1.Models.Korisnik>

@{
    ViewBag.Title = "Registrations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrations</h2>
<br />
@using (Html.BeginForm("Registrations", "Home", FormMethod.Get))
{
    <p>
        @Html.DropDownList("filter", "sve")
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrTokena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Uloga)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrTokena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uloga)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Korisniks", new { id = item.IdKor }, null) 
            </td>
        </tr>
    }

</table>

iep_projekat/WebRole1/Views/Home/Tokens.cshtml
@{
    ViewBag.Title = "Tokens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tokens</h2>

<h4>Trenutno stanje tokena: <font size="10"><b>&nbsp;@ViewBag.tokens</b></font></h4>

<br/>

<h4>Dopuni se jednim od paketa: </h4>
<br />
<div class="row">
    <div class="col-md-2">
        <form action=@ViewBag.link >
            <input type="button" value="SILVER @ViewBag.silver" class="btn btn-default" onclick="window.location.href='/Home/Order?numOfTokens=@ViewBag.silver'"/>
        </form>
    </div>
    <div class="col-md-2">
        <input type="button" value="GOLD @ViewBag.gold" class="btn btn-default" onclick="window.location.href='/Home/Order?numOfTokens=@ViewBag.gold'"/>
    </div>
    <div class="col-md-2">
        <input type="button" value="PLATIN @ViewBag.platin" class="btn btn-default" onclick="window.location.href='/Home/Order?numOfTokens=@ViewBag.platin'"/>
    </div>
</div>

<br /><br />
@Html.ActionLink("Prethodne narudzbine", "Index", "Narudzbinas")

iep_projekat/WebRole1/Views/Home/UnauthorizedAccess.cshtml
@{
    ViewBag.Title = "UnauthorizedAccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nedozvoljen pristup!</h1>