iep_projekat/WebRole1/Models/Pitanje.cs
namespace WebRole1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("Pitanje")]
    public partial class Pitanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pitanje()
        {
            Klons = new HashSet<Klon>();
            PonudjeniOdgs = new HashSet<PonudjeniOdg>();
        }

        [Key]
        public int IdPit { get; set; }

        [StringLength(80)]
        [Required]
        public string Naslov { get; set; }

        [Column(TypeName = "text")]
        [Required]
        public string Tekst { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageToUpload { get; set; }

        public byte[] Slika { get; set; }

        [Display(Name = "Vreme Pravljenja")]
        public DateTime VrPravljenja { get; set; }

        [Display(Name = "Vreme Zakljucavanja")]
        public DateTime? VrPoslZaklj { get; set; }

        public bool Zakljucano { get; set; }

        public int IdKor { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klon> Klons { get; set; }

        public virtual Korisnik Korisnik { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PonudjeniOdg> PonudjeniOdgs { get; set; }
    }
}

iep_projekat/WebRole1/Controllers/PitanjesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class PitanjesController : Controller
    {
        private baza db = new baza();

        public Korisnik getKorisnik()
        {
            if (Session["email"] != null)
            {
                string email = Session["email"].ToString();
                Korisnik korisnik = db.Korisniks.Where(a => a.Email.Equals(email)).FirstOrDefault<Korisnik>();

                return korisnik;
            }
            else
            {
                return null;
            }
        }

        // GET: Pitanjes
        public ActionResult Index()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Korisnik korisnik = getKorisnik();
            var pitanjes = db.Pitanjes.Where(p => p.IdKor == korisnik.IdKor).Include(p => p.Korisnik);
            return View(pitanjes.ToList());
        }

        // GET: Pitanjes/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = db.Pitanjes.Find(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            ViewBag.K = (int)db.Parametris.FirstOrDefault<Parametri>().K;
            return View(pitanje);
        }

        // GET: Pitanjes/Create
        public ActionResult Create()
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Parametri parametri = db.Parametris.FirstOrDefault<Parametri>();
            ViewBag.K = parametri.K;
            ViewBag.IdKan = new SelectList(db.Kanals, "IdKan", "Naziv");
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime");
            return View();
        }

        // POST: Pitanjes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pitanje pitanje)
        {
            ViewBag.K = db.Parametris.FirstOrDefault().K;
            if (ModelState.IsValid)
            {
                Korisnik korisnik = getKorisnik();
                int K = (int)db.Parametris.FirstOrDefault<Parametri>().K;

                // Convert HttpPostedFileBase to byte array.
                if(pitanje.ImageToUpload != null)
                {
                    pitanje.Slika = new byte[pitanje.ImageToUpload.ContentLength];
                    pitanje.ImageToUpload.InputStream.Read(pitanje.Slika, 0, pitanje.Slika.Length);
                }
                pitanje.VrPravljenja = DateTime.Now;
                pitanje.IdKor = korisnik.IdKor;
                if (pitanje.Zakljucano == true)
                    pitanje.VrPoslZaklj = DateTime.Now;

                int tacanOdgovor = Convert.ToInt32(Request["radioPonudjeno"]);
                for(int i = 0; i < K; i++)
                {
                    string tekstPonudjenog = Request["ponudjeno" + i].ToString();
                    if (tekstPonudjenog == "")
                    {
                        ModelState.AddModelError(string.Empty, "Uneti ponudjene odgovore");
                        return View(pitanje);
                    }
                    PonudjeniOdg ponudjeni = new PonudjeniOdg();
                    ponudjeni.IdPit = pitanje.IdPit;
                    ponudjeni.Sadrzaj = tekstPonudjenog;
                    ponudjeni.RedniBr = i;
                    ponudjeni.Tacan = (i == tacanOdgovor ? true : false);
                    
                    db.PonudjeniOdgs.Add(ponudjeni);
                }

                db.Pitanjes.Add(pitanje);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", pitanje.IdKor);
            return View(pitanje);
        }

        // GET: Pitanjes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = db.Pitanjes.Find(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            if (pitanje.Zakljucano == true)
            {
                return RedirectToAction("UnlockQuestion", new { id = id });
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", pitanje.IdKor);
            ViewBag.K = db.Parametris.FirstOrDefault().K;
            return View(pitanje);
        }

        // POST: Pitanjes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pitanje pitanje)
        {
            if (ModelState.IsValid)
            {
                ViewBag.K = db.Parametris.FirstOrDefault().K;
                if (pitanje.Zakljucano == true)
                {
                    pitanje.VrPoslZaklj = DateTime.Now;
                }

                int K = (int)db.Parametris.FirstOrDefault<Parametri>().K;
                int tacanOdgovor = Convert.ToInt32(Request["radioPonudjeno"]);
                for (int i = 0; i < K; i++)
                {
                    string tekstPonudjenog = Request["ponudjeno" + i].ToString();
                    if(tekstPonudjenog == "") {
                        ModelState.AddModelError(string.Empty, "Uneti ponudjene odgovore");
                        pitanje.PonudjeniOdgs = db.PonudjeniOdgs.Where(p => p.IdPit == pitanje.IdPit).ToList();
                        return View(pitanje);
                    }
                    PonudjeniOdg ponudjeni = db.PonudjeniOdgs.Where(p => p.IdPit == pitanje.IdPit).Where(p => p.RedniBr == i).FirstOrDefault();
                    ponudjeni.Sadrzaj = tekstPonudjenog;
                    ponudjeni.Tacan = (i == tacanOdgovor ? true : false);

                    db.Entry(ponudjeni).State = EntityState.Modified;
                }

                db.Entry(pitanje).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKor = new SelectList(db.Korisniks, "IdKor", "Ime", pitanje.IdKor);
            return View(pitanje);
        }

        // GET: Pitanjes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = db.Pitanjes.Find(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            return View(pitanje);
        }

        // POST: Pitanjes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pitanje pitanje = db.Pitanjes.Find(id);
            db.Pitanjes.Remove(pitanje);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UnlockQuestion(int id)
        {
            if (Session["uloga"] == null || Session["uloga"].ToString() != "profesor")
            {
                return RedirectToAction("UnauthorizedAccess");
            }

            Parametri parametri = db.Parametris.FirstOrDefault<Parametri>();
            Pitanje pitanje = db.Pitanjes.Find(id);
            ViewBag.M = parametri.M;
            return View(pitanje);
        }

        [HttpPost, ActionName("UnlockQuestion")]
        [ValidateAntiForgeryToken]
        public ActionResult UnlockConfirmation(int id)
        {
            Korisnik korisnik = getKorisnik();
            Parametri parametri = db.Parametris.FirstOrDefault<Parametri>();
            Pitanje pitanje = db.Pitanjes.Find(id);

            if (korisnik.BrTokena < parametri.M)
            {
                return RedirectToAction("NotEnoughTokens");
            }

            korisnik.BrTokena -= (int)parametri.M;
            korisnik.PotvrdaLozinke = korisnik.Lozinka;
            pitanje.Zakljucano = false;

            db.Entry(pitanje).State = EntityState.Modified;
            db.Entry(korisnik).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult NotEnoughTokens()
        {
            return View();
        }

        
    }
}

iep_projekat/WebRole1/Views/Pitanjes/Create.cshtml
@model WebRole1.Models.Pitanje

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pitanjes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pitanje</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naslov, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tekst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tekst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tekst, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageToUpload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageToUpload, new { type = "file" })
                @*<input name="upload" type="file" />*@
                @*@Html.ValidationMessageFor(model => model.Slika, "", new { @class = "text-danger" })*@
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Zakljucano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Zakljucano)
                    @Html.ValidationMessageFor(model => model.Zakljucano, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2"><b>Ponudjeni odgovori</b></p>
            <div class="col-md-10">
                @{ int num = ViewBag.K; }
                @for(int i = 0; i < num; i++)
                {
                    @Html.TextBox("ponudjeno" + i, null, htmlAttributes: new { @class = "form-control col-md-8" })  
                    <div class="col-md-2">
                        @if(i == 0)
                        {
                            @Html.RadioButton("radioPonudjeno", i, true)
                        }
                        else
                        {
                            @Html.RadioButton("radioPonudjeno", i)
                        }
                    </div>
                    <br /> <br />
                }
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iep_projekat/WebRole1/Views/Pitanjes/Delete.cshtml
@model WebRole1.Models.Pitanje

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pitanje</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kanal.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kanal.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naslov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tekst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tekst)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Slika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slika)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.VrPravljenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPravljenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPoslZaklj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPoslZaklj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zakljucano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zakljucano)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iep_projekat/WebRole1/Views/Pitanjes/Details.cshtml
@model WebRole1.Models.Pitanje

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Pitanje</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Kanal.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kanal.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naslov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tekst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tekst)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slika)
        </dt>

        <dd>
            @if (Model.Slika != null)
            {
                @HtmlHelpers.ShowImage(Model.Slika);
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPravljenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPravljenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPoslZaklj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPoslZaklj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zakljucano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zakljucano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PonudjeniOdgs)
        </dt>

        @for(int i = 0; i < Convert.ToInt32(ViewBag.K); i++)
        {
            <dd>
                @Html.DisplayFor(model => model.PonudjeniOdgs.Where(p => p.IdPit == model.IdPit).Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj)
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPit }) |
    @Html.ActionLink("Back to List", "Index")
</p>

iep_projekat/WebRole1/Views/Pitanjes/Edit.cshtml
@model WebRole1.Models.Pitanje

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pitanje</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPit)
        @Html.HiddenFor(model => model.IdKor)

        <div class="form-group">
            @Html.LabelFor(model => model.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naslov, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tekst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tekst, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tekst, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Slika, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slika, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slika, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.VrPravljenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrPravljenja, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.VrPravljenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrPoslZaklj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VrPoslZaklj, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.VrPoslZaklj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zakljucano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Zakljucano)
                    @Html.ValidationMessageFor(model => model.Zakljucano, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2"><b>Ponudjeni odgovori</b></p>
            <div class="col-md-10">
                @{ int num = ViewBag.K; }
                @for (int i = 0; i < num; i++)
                {
                    @Html.TextBox("ponudjeno" + i, Model.PonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Sadrzaj , htmlAttributes: new { @class = "form-control col-md-8" })
                    <div class="col-md-2">
                        @if (Model.PonudjeniOdgs.Where(p => p.RedniBr == i).FirstOrDefault().Tacan == true)
                        {
                            @Html.RadioButton("radioPonudjeno", i, true)
                        }
                        else
                        {
                            @Html.RadioButton("radioPonudjeno", i)
                        }
                    </div>
                    <br /> <br />
                }
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IdKor, "IdKor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdKan, "IdKan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKan", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKan, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

iep_projekat/WebRole1/Views/Pitanjes/Index.cshtml
@model IEnumerable<WebRole1.Models.Pitanje>

@{
    ViewBag.Title = "Questions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Questions</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.Kanal.Naziv)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.IdPit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naslov)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Tekst)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.Slika)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.VrPravljenja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrPoslZaklj)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zakljucano)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Kanal.Naziv)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.IdPit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naslov)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Tekst)
                </td>
                <td>
                    @if (item.Slika != null)
                    {
                        @HtmlHelpers.ShowImage(item.Slika);
                    }
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.VrPravljenja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrPoslZaklj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zakljucano)
            </td>
            <td>
                @if (item.Zakljucano == true)
                {
                    @Html.ActionLink("Unlock", "Edit", new { id = item.IdPit })
                }
                else
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.IdPit })
                }
                | @Html.ActionLink("Details", "Details", new { id = item.IdPit })
            </td>
        </tr>
    }

</table>

iep_projekat/WebRole1/Views/Pitanjes/NotEnoughTokens.cshtml
@{
    ViewBag.Title = "NotEnoughTokens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Not enough tokens!</h1>

iep_projekat/WebRole1/Views/Pitanjes/UnlockQuestion.cshtml
@model WebRole1.Models.Pitanje

@{
    ViewBag.Title = "UnlockQuestion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Question is locked!</h2>

<h3>Do you want to unlock it for <b>@ViewBag.M</b> tokens?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Kanal.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kanal.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.Ime)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naslov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tekst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tekst)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Slika)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Slika)
            </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.VrPravljenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPravljenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrPoslZaklj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrPoslZaklj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zakljucano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zakljucano)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Unlock" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>